AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: A lightweight, general purpose object detection endpoint.

# Add Parameters section
Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  StackName:
    Type: String
    Description: The name of the stack (used for SSM parameter lookup)
  AppName:
    Type: String
    Default: ophanim
    Description: The application name (matches the SSM parameter prefix)

Conditions:
  HasCustomDomain: !Equals [!Ref Environment, prod]

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 2048
    Tracing: Active
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'*'"

Resources:
  DetectionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./detection
      DockerTag: v1
    Properties:
      # FunctionName: !Sub "${AWS::StackName}"
      PackageType: Image
      CodeUri: detection/
      # Handler: app.lambda_handler
      # Runtime: python3.12
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 4096
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/detection:*
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          APP_NAME: !Ref AppName
      SnapStart:
        ApplyOn: None
      Events:
        DetectGet:
          Type: Api
          Properties:
            Path: /detect
            Method: get
        DetectPost:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /detect
            Method: post
        DetectOptions: # Add this new event
          Type: Api
          Properties:
            Path: /detect
            Method: options

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: true

  ApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Condition: HasCustomDomain
    Properties:
      DomainName: !Sub "{{resolve:ssm:/${AppName}/${StackName}/domain_name}}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Sub "{{resolve:ssm:/${AppName}/${StackName}/domain_name}}"
          HostedZoneId: !Sub "{{resolve:ssm:/${AppName}/${StackName}/hosted_zone_id}}"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Condition: HasCustomDomain
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Sub "{{resolve:ssm:/${AppName}/${StackName}/domain_name}}"
        ViewerCertificate:
          AcmCertificateArn: !Ref ApiCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - Id: ApiGatewayOrigin
            DomainName: !Sub "${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com"
            OriginPath: /Prod
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
        DefaultCacheBehavior:
          TargetOriginId: ApiGatewayOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - HEAD
            - DELETE
            - POST
            - GET
            - OPTIONS
            - PUT
            - PATCH
          CachedMethods:
            - HEAD
            - GET
          ForwardedValues:
            QueryString: true
            Headers:
              - Authorization
            Cookies:
              Forward: none
        HttpVersion: http2

  Route53RecordSet:
    Type: AWS::Route53::RecordSet
    Condition: HasCustomDomain
    Properties:
      HostedZoneId: !Sub "{{resolve:ssm:/${AppName}/${StackName}/hosted_zone_id}}"
      Name: !Sub "{{resolve:ssm:/${AppName}/${StackName}/domain_name}}"
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront Hosted Zone ID (Fixed for all distributions)
        DNSName: !GetAtt CloudFrontDistribution.DomainName

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DetectionApi:
    Description: API Gateway endpoint URL for Prod stage for Detection function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/detect"
  DetectionFunction:
    Description: Ophanim Lambda Function ARN
    Value: !GetAtt DetectionFunction.Arn
  DetectionFunctionIamRole:
    Description: Implicit IAM Role created for Detection function
    Value: !GetAtt DetectionFunctionRole.Arn
  CloudFrontDistribution:
    Description: CloudFront Distribution Domain Name
    Condition: HasCustomDomain
    Value: !GetAtt CloudFrontDistribution.DomainName
  CustomDomain:
    Description: Custom Domain URL
    Condition: HasCustomDomain
    Value: !Sub "https://{{resolve:ssm:/${AppName}/${StackName}/domain_name}}"
